# Generated by Django 5.1.2 on 2024-10-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_emailsite_alter_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='message',
            new_name='comment',
        ),
    ]
