# Generated by Django 5.1.2 on 2024-10-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_message_email_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policychanges',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='blog.privacypolicy'),
        ),
    ]
